---
- name: Configure Ubuntu Server for blog hosting
  hosts: all

  vars:
    - project_root: /opt/site
    - project_admin: deploy
    - system_packages:
        - htop
        - tree
        - jq
        - fail2ban
        - vim
        - mosh
        - ufw

  tasks:
    - name: Create Docker group
      group: name=docker state=present

    - name: Create the project directory
      file: state=directory path={{project_root}}

    - name: Create deploy user
      user: home=/home/{{project_admin}} name={{project_admin}} groups=docker,{{project_admin}} state=present

    - name: Add SSH authorized key
      authorized_key: user={{project_admin}} key="{{ lookup('file', '/root/.ssh/id_rsa_deploy.pub') }}"

    - name: Project directory permission
      file: state=directory path={{project_root}} owner={{project_admin}} group={{project_admin}}

    - name: Update the project directory
      file: group={{project_admin}} owner={{project_admin}} mode=755 state=directory path={{project_root}}

    - name: Install required system packages
      apt: pkg={{ item }} state=installed update-cache=yes
      with_items: system_packages

    - name: Install Docker Compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

    - name: Modify Docker Compose Command
      file: group=docker mode=774 state=file path=/usr/local/bin/docker-compose

    - name: Reset UFW firewall
      ufw:
        state=reset

    - name: Allow SSH access on instance
      ufw: >
        rule=allow
        name=OpenSSH

    - name: Open Docker daemon, HTTP(S), and Swarm ports
      ufw: >
        rule=allow
        port={{ item }}
        proto=tcp
      with_items:
        - 80     # Default HTTP port
        - 443    # Default HTTPS port
        - 2375   # Docker daemon API port (non-TLS)
        - 2376   # Docker daemon API port (TLS)
        - 3376   # Swarm API port

    - name: Set to deny incoming requests by default
      ufw: >
        default=deny

    - name: Turn on UFW
      ufw: >
        state=enabled

    - name: Turn Off SSH password login
      lineinfile: >
        dest=/etc/ssh/sshd_config
        regexp=#PasswordAuthentication
        line='PasswordAuthentication no'

    - name: Turn Off Challengeresponseauthentication
      lineinfile: >
        dest=/etc/ssh/sshd_config
        regexp=ChallengeResponseAuthentication
        line='ChallengeResponseAuthentication no'

    - name: Set memory limit in GRUB
      lineinfile: >
        dest=/etc/default/grub
        regexp=^GRUB_CMDLINE_LINUX_DEFAULT
        line='GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"'

    - name: Load new GRUB config
      command: update-grub

    - name: Set hostname
      hostname: name={{ inventory_hostname }}

    - name: Set properly in /etc/hosts
      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 {{ inventory_hostname }}' owner=root group=root mode=0644
